apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  repo: https://github.com/PLACEHOLDER_ORG/PLACEHOLDER_REPO
  branch: main
  paths:
    - ./clusters/management
